### ISSUE TITLE
NameError: name 'boxing_v2' is not defined

### ISSUE THREAD

**Issue by hwz9612** [quantumiracle/nash-dqn#2]
Hi,
When I executed the following command, I encountered the problem.
`python launch.py --env pettingzoo_boxing_v2 --method nash_dqn`
The problem:
`Traceback (most recent call last):
  File "/home/heweizhen/exper_code/nash-dqn/launch.py", line 169, in <module>
    env = eval(args.env_name).parallel_env(obs_type=obs_type, full_action_space=False)
  File "<string>", line 1, in <module>
NameError: name 'boxing_v2' is not defined`
According to your offered requirement.txt, I have installed the gym==0.22.0
What can I do?

**Comment by hwz9612** [comment]
Hi,
I have solved this problem. Thanks.

**Comment by time-TT** [comment]
How was this problem solved
