### ISSUE TITLE
Can this method solve the non-zero sum game?

### ISSUE THREAD

**Issue by hwz9612** [quantumiracle/nash-dqn#4]
Hi,
Can this method solve the non-zero sum game?
Thanks.

**Comment by quantumiracle** [comment]
Hi, 

Yes. It can be extended to general-sum games for solving Nash equilibrium (NE) or coarse correlated equilibrium (CCE), by plugging in [NE or CCE solvers](https://github.com/quantumiracle/nash-dqn/blob/9e8080962046f2ce2cf5782b0311a0b61d9804bd/equilibrium_solver/eq_LPsolver.py#L78) for general-sum, in place of [default solver for zero-sum](https://github.com/quantumiracle/nash-dqn/blob/9e8080962046f2ce2cf5782b0311a0b61d9804bd/nash_dqn.py#L88).

But the performance of these general-sum solvers is not guaranteed. Some exploration and changes may be required here.
