### ISSUE TITLE
general-sum nash

### ISSUE THREAD

**Issue by hwz9612** [quantumiracle/nash-dqn#5]
Hi,
Recently, I solve the general-sum nash equilibrium by modify the code. But I meet with one problem. How can I modify the update function? When we solve zero-sum nash equilibrium, we only construct a network and get a q-values. When we solve general-sum nash equilibrium, do I construct two network?

**Comment by quantumiracle** [comment]
Hi,

Yes, I think it should either has two networks or a shared network body with two heads.
